# Generated by Django 3.0 on 2020-01-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='isStaff',
        ),
    ]
