# Generated by Django 3.0 on 2020-01-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200105_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_Admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isStaff',
            new_name='is_Staff',
        ),
    ]
