# Generated by Django 3.0 on 2020-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
